name: helloworld

on:
  push:
    branches:
      - main

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Hello World
        uses: dagger/dagger-for-github@v2
        with:
          version: 0.2
          cmds: |
            do hello --log-format=plain
